# Generated by Django 5.2.1 on 2025-05-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_employee_name_remove_order_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='calories',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(blank=True, choices=[('burger', 'Burger'), ('dessert', 'Dessert'), ('drink', 'Drink'), ('fast', 'Fast Food')], max_length=50, null=True),
        ),
    ]
