# Generated by Django 5.2.1 on 2025-05-20 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='secret_password',
        ),
    ]
