# Generated by Django 5.2.1 on 2025-05-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_employee_id_alter_menuitem_id_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.PositiveIntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
